package com.zhuinden.realmautomigrationexample;

/**
 * Created by Zhuinden on 2017.09.24..
 */

public enum CatNames {
    BUBBLES("Bubbles"),
    BUNDLES("Bundles"),
    BUNNY("Bunny"),
    BUTTERCUP("Buttercup"),
    BUTTON("Button"),
    CHIPMUNK("Chipmunk"),
    CINNAMON("Cinnamon"),
    CUDDLES("Cuddles"),
    DAISY("Daisy"),
    DIMPLES("Dimples"),
    HICCUP("Hiccup"),
    HUGGIE("Huggie"),
    JELLYBEAN("Jellybean"),
    JIGGLES("Jiggles"),
    JUJUBE("Jujube"),
    KITKAT("Kitkat"),
    LOLLIPOP("Lollipop"),
    MARSHMALLOW("Marshmallow"),
    MUNCHKIN("Munchkin"),
    NIBBLES("Nibbles"),
    NUGGET("Nugget"),
    PANDA("Panda"),
    PEACHES("Peaches"),
    PICKLES("Pickles"),
    PIXIE("Pixie"),
    POCKET("Pocket"),
    SCHMOOPY("Schmoopy"),
    SKITTLES("Skittles"),
    SNICKERS("Snickers"),
    SNOWBALL("Snowball"),
    SNUGGLES("Snuggles"),
    SQUIGGLE("Squiggle"),
    TAFFY("Taffy"),
    TEACUP("Teacup"),
    TIPSY("Tipsy"),
    TWINKLES("Twinkles"),
    VELVET("Velvet"),
    WAFFLES("Waffles"),
    WIGGLES("Wiggles"),
    WINKY("Winky"),
    BAMBI("Bambi"),
    BARBIE("Barbie"),
    BLOSSOM("Blossom"),
    BLUEBELL("Bluebell"),
    CALYPSO("Calypso"),
    COOKIE("Cookie"),
    CUPCAKE("Cupcake"),
    ELECTRA("Electra"),
    GIGGLES("Giggles"),
    GINGER("Ginger"),
    GOLDILOCKS("Goldilocks"),
    GUMDROP("Gumdrop"),
    HONEYBEE("Honeybee"),
    JASMINE("Jasmine"),
    JULIETTE("Juliette"),
    JUNIPER("Juniper"),
    LADYBUG("Ladybug"),
    LAKSHMI("Lakshmi"),
    MISTY("Misty"),
    NUTMEG("Nutmeg"),
    OLYMPIA("Olympia"),
    PRINCESS("Princess"),
    RUBY("Ruby"),
    TIARA("Tiara"),
    TINKERBELL("Tinkerbell"),
    TRIXIE("Trixie"),
    TWINKLE("Twinkle"),
    VENUS("Venus"),
    AMIGO("Amigo"),
    BANJO("Banjo"),
    COSMO("Cosmo"),
    CROCKET("Crocket"),
    DONATELLO("Donatello"),
    ELECTRO("Electro"),
    ELVIS("Elvis"),
    EURIPIDES("Euripides"),
    FIGARO("Figaro"),
    FONZIE("Fonzie"),
    GALILEO("Galileo"),
    GERONIMO("Geronimo"),
    HENDRIX("Hendrix"),
    HERCULES("Hercules"),
    HOBBES("Hobbes"),
    HOUDINI("Houdini"),
    LANCELOT("Lancelot"),
    MARS("Mars"),
    MOSES("Moses"),
    OZZY("Ozzy"),
    PHARAOH("Pharaoh"),
    PICASSO("Picasso"),
    PRINCE("Prince"),
    REMBRANDT("Rembrandt"),
    ROMEO("Romeo"),
    RUMI("Rumi"),
    SIMBA("Simba"),
    TARZAN("Tarzan"),
    WIZARD("Wizard"),
    ZORRO("Zorro");

    private String name;

    private CatNames(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
